web/Controllers/ReporteSaldoTecnicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text;
using web.Utils;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Web.Controllers;
using web.Models;

namespace web.Controllers
{
    public class ReporteSaldoTecnicoController : Controller
    {
        //
        // GET: /ReporteSaldoTecnico/
        [SessionExpireFilterAttribute]
        public ActionResult Index()
        {
            ModeloAlmacen dc = new ModeloAlmacen();
            Usuario u = ((Usuario)Session["u"]);
            List<Entidad> lista_tecnicos = (from a in dc.Entidad
                                            join b in dc.AmbitoAlmacen on a.EntidadClave equals b.EntidadClaveTecnico
                                            where  a.catDistribuidorClave ==u.DistribuidorClave   && a.catEntidadTipoClave == 2
                                            select a).ToList();


            var tecgen = (from a in dc.Entidad
                          join b in dc.RelTecnicoDistribuidor on a.EntidadClave equals b.EntidadClave
                          where b.DistribuidorClave == u.DistribuidorClave
                          select a).ToList();

            lista_tecnicos.AddRange(tecgen);
            ViewData["tecnicos"] = lista_tecnicos.OrderBy(p=>p.Nombre).ToList();
            return View();
        }



        public ActionResult getTipoArticulo()
        {
            ModeloAlmacen dc = new ModeloAlmacen();
            var lista = dc.catTipoArticulo.Where(x => x.Activo == true && x.catSerieClaveInterface!=null).Select(o => new { o.Descripcion, o.catTipoArticuloClave }).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getArticulos(int id_categoria)
        {
            ModeloAlmacen dc = new ModeloAlmacen();
            var lista = dc.Articulo.Where(x => x.catTipoArticuloClave == id_categoria).Select(o => new { o.Nombre, o.ArticuloClave }).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detalle()
        {
            int pdf = Convert.ToInt32(Request["pdf"]);


            Guid tecnico = Guid.Empty;
            try
            {
                tecnico = new Guid(Request["tecnico"].ToString());
            }
            catch
            {}

            Guid articulo = Guid.Empty;
            try
            {
                articulo = new Guid(Request["articulo"].ToString());
            }
            catch
            { }
            ModeloAlmacen dc = new ModeloAlmacen();
            List<reporte_lista> lista = new List<reporte_lista>();            
            StringBuilder sb = new StringBuilder();
            String empresa = Config.Dame("EMPRESA");
            string logo = Config.Dame("LOGO_ENTRADA");
            sb.Append(@"<table cellpadding=""2""  cellspacing=""0"" border=0 width=""100%"">");
            sb.Append("<tr>");
            sb.Append(@"<td align=""center"">");
            sb.Append("<h3><b>" + empresa + "</b></h3>");
            sb.Append("<h4><b>APARATOS DE TÉCNICO</b></h4>");
            // sb.Append("<b>Periodo del:</b> " + fechaInicio + "<b> al: </b> " + fechaFin + "<br>");
            if (articulo == Guid.Empty)
            {
                sb.Append("<b>Artículos:</b>Todos los artículos <br>");
            }
            else
            {
                Articulo art = dc.Articulo.Where(o => o.ArticuloClave == articulo).First();
                sb.Append("<b>Artículos:</b>" + art.Nombre + " <br>");
            }
            sb.Append("<b>Fecha: " + DateTime.Now.ToShortDateString() + "</b><br>");


            sb.Append("</td>");
            //sb.Append(@"<td align=""right"">");
            //sb.Append("<img src='_RUTA_/media/" + logo + "' width=90 height=80 align=right><br>");
            sb.Append("</tr>");
            sb.Append("</table>");

            List<Articulo> articuloslista = (from aa in dc.Articulo where articulo == Guid.Empty 
                                             || articulo == aa.ArticuloClave orderby aa.Nombre
                                             select aa).ToList();

            List<Entidad> tecnicoslista = (from aa in dc.Entidad
                                             where tecnico == Guid.Empty
                                              || tecnico == aa.EntidadClave
                                             orderby aa.Nombre
                                             select aa).ToList();
            tecnicoslista.ForEach(tec  => {

                List<Serie> seriest = (from s in dc.Serie
                                      where s.Inventario.EntidadClave == tec.EntidadClave                                      
                                      select s).ToList();
                if(seriest.Count > 0)
                {
                    //sb.Append("<br>");
                    sb.Append(@"<b style=""font-size:9px"" >Técnico: </b><span style=""font-size:8px"">" + tec.Nombre+"</span>");
                    sb.Append("<br>");
                   // sb.Append("_____________________________________");
                    sb.Append("<br>");

                    articuloslista.ForEach(x=> {
                 
                    List<Serie> series = (from s in dc.Serie
                                          where s.Inventario.EntidadClave == tec.EntidadClave
                                          && s.Inventario.ArticuloClave == x.ArticuloClave
                                          select s).ToList();

                    if(series.Count > 0)
                    {
                        

                        sb.Append(@"<table cellpadding=""2""  cellspacing=""0"" border=0 width=""100%"">");
                        sb.Append("<tr>");
                        sb.Append(@"<td style=""font-size:8px;text-decoration: underline;"">Clasificación:</td>");
                        sb.Append(@"<td style=""font-size:8px;text-decoration: underline;"">Tipo de Artículo:</td>");
                        sb.Append(@"<td style=""font-size:8px;text-decoration: underline;"">Artículo:</td>");
                        sb.Append(@"<td style=""font-size:8px;text-decoration: underline;"" >Serie</td>");
                        sb.Append("</tr>");

                        series.ForEach(se =>
                        {
                            sb.Append("<tr>");
                            sb.Append(@"<td style=""font-size:8px;"">" + se.Inventario.Articulo.catTipoArticulo.catClasificacionArticulo.Descripcion+"</td>");
                            sb.Append(@"<td style=""font-size:8px;"">" + se.Inventario.Articulo.catTipoArticulo.Descripcion+"</td>");
                            sb.Append(@"<td style=""font-size:8px;"">" + se.Inventario.Articulo.Nombre+"</td>");
                            sb.Append(@"<td style=""font-size:8px;"">" + se.Valor+"</td>");
                            sb.Append("</tr>");

                        });

                            sb.Append("<tr>");
                            sb.Append(@"<td colspan=3></td>");                            
                            sb.Append(@"<td style=""font-size:8px;""> <b>Total:</b> " + series.Count + "</td>");
                            sb.Append("</tr>");

                            sb.Append(@"</table>");
                    }
                    

                });
                }
                
            });

            


            if (pdf != 1 && pdf != 2)
            {
                ViewData["html"] = sb.ToString().Replace(@"bgcolor=""#424242""", "").Replace(@"color=""#FFFFFF""", "").Replace("border=1", "").Replace("_RUTA_", "/Content");
                return View();
            }
            else
            {

                PDF elpdf = new PDF();

                Guid g = Guid.NewGuid();

                string rutaarchivo = Server.MapPath("/Content") + "/media/" + g.ToString() + ".pdf";

                elpdf.HTMLToPdf(sb.ToString().Replace("_RUTA_", Server.MapPath("/Content")), rutaarchivo, null);


                if (pdf == 1)
                {
                    ViewData["html"] = "<iframe id='unIframe' src='" + "/Content/media/" + g.ToString() + ".pdf" + "' frameborder=0  scrolling='no' width='100%' style='height: 100vh;'></iframe>";

                    return View();
                }
                else
                {
                    ViewData["html"] = "<iframe id='unIframe' src='" + "/Content/media/" + g.ToString() + ".pdf" + "' frameborder=0  scrolling='no' width='100%' style='height: 100vh;'></iframe>";

                    return View();
                }
            }
        }


        //public ActionResult getAlamcen(System.Guid id_distribuidor)
        //{
        //    ModeloAlmacen dc = new ModeloAlmacen();
        //    var lista = dc.Entidad.Where(x => x.catDistribuidorClave == id_distribuidor && x.catEntidadTipoClave == 1).Select(o => new { o.EntidadClave, o.Nombre }).ToList();
        //    return Json(lista.OrderBy(x => x.Nombre), JsonRequestBehavior.AllowGet);
        //}
        //public ActionResult getTecnicos(System.Guid id_almacen)
        //{
        //    ModeloAlmacen dc = new ModeloAlmacen();
        //    var lista = (from a in dc.Entidad join b in dc.AmbitoAlmacen on a.EntidadClave equals b.EntidadClaveTecnico where b.EntidadClaveAlmacen == id_almacen select new { a.Nombre, a.EntidadClave }).ToList();

        //    Entidad almacen = dc.Entidad.Where(x => x.EntidadClave == id_almacen).First();
        //    var tecgen = (from a in dc.Entidad
        //                  join b in dc.RelTecnicoDistribuidor on a.EntidadClave equals b.EntidadClave
        //                  where b.DistribuidorClave == almacen.catDistribuidorClave
        //                  select new { a.Nombre, a.EntidadClave }).ToList();

        //    lista.AddRange(tecgen);

web/Views/ReporteSaldoTecnico/Detalle.cshtml
<link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css' />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/bootstrap.css?1422792965" />
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/materialadmin.css?1425466319" />
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/font-awesome.min.css?1422529194" />
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/material-design-iconic-font.min.css?1421434286" />
<!-- END STYLESHEETS -->
@{
    ViewBag.Title = "Detalle";

}

<script>
    $(document).ready(function () {
        $("body").tooltip({ selector: '[data-toggle=tooltip]' });

    });


</script>


<a href="@Url.Action("Index", "ReporteSaldoTecnico")" class=" btn ink-reaction btn-floating-action btn-success" data-toggle='tooltip' data-placement='right' title='' data-original-title='Regresa al reporte' style="position:absolute; top:100px;left:100px; ">
    <i class="fa fa-hand-o-left"></i>
</a>

@Html.Raw(ViewData["html"])

<script src="~/Content/assets/js/libs/jquery/jquery-migrate-1.2.1.min.js"></script>
<script src="~/Content/assets/js/libs/bootstrap/bootstrap.min.js"></script>
<script src="~/Content/assets/js/libs/toastr/toastr.js"></script>

web/Views/ReporteSaldoTecnico/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Plantilla.cshtml";
   List<web.Models.Entidad> tecnicos = (List<web.Models.Entidad>)ViewData["tecnicos"];
}


<div class="card" id="filtros" >
  
    <div class="card-head style-default-light" style="padding-top:10px; padding-left:10px;">
        <header>
            <strong style="font-weight:bold; border:none;">Equipos de técnicos</strong>
            <br /><small class="text-muted" style="font-size:14px;"> <a href="#"><i class="fa fa-home" aria-hidden="true"></i> Inicio</a>><a href="#" class="paginaActiva">Reportes</a></small>

        </header>
        <div class="tools">
            <div class="btn-group">
                <div class="btn-group open">
                    <a href="#" class="btn btn-icon-toggle dropdown-toggle" data-toggle="dropdown" aria-expanded="true"><i class="md md-content-paste"></i></a>
                    <ul class="dropdown-menu animation-dock pull-right" role="menu" style="text-align: left;">
                        <li><a href="javascript:void(0); " id="btn-reporte" onclick="generarReporte()" disabled><i class="fa fa-circle fa-fw text-default-dark"></i>Formato PDF</a></li>
                        <
                        @*<li><a href="javascript:void(0);" id="obtenexcel"><i class="fa fa-circle fa-fw text-muted"></i> Formato Excel</a></li>*@

                    </ul>
                </div>
                <a class="btn btn-icon-toggle btn-refresh"><i class="md md-refresh"></i></a>
                <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>

            </div>

            @*<button class="btn btn-info btn-sm" id="pdfrecepcion">Descargar reporte</button>*@
        </div>
    </div>


    <div class="card-body">

        @*<div class="col-md-4">*@

            @*<div style="margin:10px;">
                <label style=" font-weight:bold">Distribuidor: </label>
                <select id="select_distribuidor" class="form-control">
                    <option value="0">Selecciona</option>
                    @foreach (var a in distribuidor.OrderBy(x => x.Nombre))
                    {
                        <option value="@a.catDistribuidorClave">@a.Nombre</option>
                    }
                </select>
            </div>*@

            @*<div style="margin:10px;">
                <label style="font-weight:bold">Almacén:</label>
                <select id="select_almacen" class="form-control" disabled>
                    <option value="0">Selecciona</option>
                </select>
            </div>*@

        @*</div>*@

        <div class="col-md-5">

            <div style="margin:10px;">
                <div class="col-md-8">
                    <label style=" font-weight:bold"> Técnico: </label>
                </div>

                <div class="col-md-4 input-group radio" id="panel_todos">
                    <input type="checkbox" name="todos" id="todos_tecnicos" value="Todos"> Todos
                </div>

                <select id="select_tecnico" class="form-control">
                    <option value="0">Todos los técnicos</option>
                    @foreach(var a in tecnicos)
                    {
                        <option value="@a.EntidadClave">@a.Nombre</option>
                    }
                </select>
                <div style="margin:10px;">
                    <label style=" font-weight:bold">Tipo de artículo: </label>
                    <select id="select_tipos" class="form-control">
                        <option value="0">Selecciona</option>
                    </select>
                </div>

                <div style="margin:10px;">
                    <label style="font-weight:bold">Artículo:</label>
                    <select id="select_articulos" class="form-control">
                        <option value="0">seleccion</option>
                    </select>
                </div>
            </div>
        </div>



    </div>
 
    <hr />

    @*<div class="row">

        <div class="col-md-2"></div>
        <div class="col-md-2" align="center">

        </div>
        <div class="col-md-3">

            <p class="text-muted">Opciones de exportación:</p>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn ink-reaction btn-floating-action btn-sm btn-danger"
                    data-toggle='tooltip' data-placement='right' title='' data-original-title='Descargar PDF' id="btn-reporte" onclick="generarReporte()" disabled>
                <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
            </button>

        </div>




        <div class="col-md-2"></div>



    </div>*@
  






</div>


<script src="~/Content/assets/js/Alertas.js"></script>
<script>
    llenarTipoArticulo();   
    $('#select_tipos').on('change', function () {
        var id = $('#select_tipos').val();
        //if (id == 0) {
        //    $('#btn-reporte').removeAttr('disabled');
        //    $('#select_articulos').prop('disabled', true);
        //    $('#select_articulos').empty();
        //    $('#select_articulos').append('<option disabled selected>Selecciona</option>');
        //} else {
           // $('#btn-reporte').removeAttr('disabled');
           // $('#select_articulos').prop('disabled', false);
            $.ajax({
                url: "/ReporteSaldoTecnico/getArticulos/",
                type: "POST",
                data: { 'id_categoria': id },
                success: function (data, textStatus, jqXHR) {
                    console.log(data)
                    $('#select_articulos').empty();
                    $('#select_articulos').removeAttr('disabled');
                    $('#select_articulos').append('<option disabled selected>selecciona</option>');
                    for (var i = 0; i < data.length; i++) {
                        console.log(data[i].ArticuloClave, data[i].Nombre)
                        $('#select_articulos').append('<option value="' + data[i].ArticuloClave + '">' + data[i].Nombre + '</option>');
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('Error');
                }
            });
        

    });
    function llenarTipoArticulo() {
        $.ajax({
            url: "/ReporteSaldoTecnico/getTipoArticulo/",
            type: "GET",
            success: function (data, textStatus, jqXHR) {
                $('#select_tipos').empty();
                $('#select_tipos').append('<option disabled selected>Selecciona</option>');
                $('#select_tipos').append('<option value="0">Todos los tipos de artículos</option>');
                for (var i = 0; i < data.length; i++) {
                    $('#select_tipos').append('<option value="' + data[i].catTipoArticuloClave + '">' + data[i].Descripcion + '</option>');
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log('Error');
            }
        });
    }

    function generarReporte() {
        var reporte = {};
        //var distribuidor = $('#select_distribuidor option:selected').text();
        //var almacen = $('#select_almacen').val();
       // var almacen_letra = $('#select_almacen option:selected').text();
       // var tipo_articulo = $('#select_tipos').val();
        var articulo = $('#select_articulo').val();
        var tecnico = $('#select_tecnico').val();                   
        window.location.href = '/ReporteSaldoTecnico/Detalle?pdf=2&articulo=' + articulo + '&tecnico=' + tecnico;
     }
</script>