web/Controllers/SaldoTecnicoController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using web.Models;
using web.Utils;
using web.Wrappers;

namespace Web.Controllers
{
    public class SaldoTecnicoController : Controller
    {
        // GET /SaldoTecnico/

        [SessionExpireFilterAttribute]
        public ActionResult Lista()
        {
            ModeloAlmacen dc = new ModeloAlmacen();
            List<catDistribuidor> distribuidor = null;

            Usuario u = ((Usuario)Session["u"]);

            if (u.DistribuidorClave == null)
            {
                distribuidor = (from c in dc.catDistribuidor
                                where c.Activo
                                orderby c.Nombre
                                select c).ToList();
            }
            else
            {
                distribuidor = (from c in dc.catDistribuidor
                                where
                                c.catDistribuidorClave == u.DistribuidorClave
                                && c.Activo
                                orderby c.Nombre
                                select c).ToList();


            }


            ViewData["distribuidor"] = distribuidor;


            List<catPuestoTecnico> puestostecnico = (from c in dc.catPuestoTecnico
                                                         where c.Activo
                                                         orderby c.Descripcion
                                                         select c).ToList();
            ViewData["puestostecnico"] = puestostecnico;


            return View();
        }

        int elementos = 15;

        public ActionResult ObtenPaginas(string data)
        {
            ModeloAlmacen dc = new ModeloAlmacen();

            JObject jObject = (JObject)JsonConvert.DeserializeObject(data);
            int pag = Convert.ToInt32(jObject["pag"].ToString());
            Guid dis = Guid.Empty;

            if (jObject["dis"].ToString() != "-1")
            {
                dis = Guid.Parse(jObject["dis"].ToString());
            }

            int pags = (from ro in dc.Entidad
                        where ro.catEntidadTipoClave == 2
                              && (ro.catDistribuidorClave == dis || (dis == Guid.Empty && ro.catDistribuidorClave == null))
                        select ro).Count();
            int div = pags / elementos;
            if (pags % elementos == 0)
            {
                return Content((div).ToString());
            }
            else
            {
                return Content((div + 1).ToString());
            }
        }

        public ActionResult ObtenLista(string data)
        {

            JObject jObject = (JObject)JsonConvert.DeserializeObject(data);
            int pag = Convert.ToInt32(jObject["pag"].ToString());


            Guid dis = Guid.Empty;

            if (jObject["dis"].ToString() != "-1")
            {
                dis = Guid.Parse(jObject["dis"].ToString());
            }

            int skip = (pag - 1) * elementos;

            ModeloAlmacen dc = new ModeloAlmacen();

            List<Entidad> lista = new List<Entidad>();

            List<Entidad> rls = (from use in dc.Entidad
                                     where use.catEntidadTipoClave == 2
                                        && (use.catDistribuidorClave == dis || (dis == Guid.Empty && use.catDistribuidorClave == null))
                                     orderby use.Nombre
                                     select use).ToList();
            lista.AddRange(rls);
            List<Entidad> tecgen = (from a in dc.Entidad
                                     join b in dc.RelTecnicoDistribuidor on a.EntidadClave equals b.EntidadClave
                                     join use in dc.catDistribuidor on b.DistribuidorClave equals use.catDistribuidorClave
                                    where (use.catDistribuidorClave == dis || (dis == Guid.Empty && use.catDistribuidorClave == null))
                                    select a ).ToList();
            lista.AddRange(tecgen);
            
           

            List<TecnicoWrapper> rw = new List<TecnicoWrapper>();

            foreach (Entidad u in rls.Skip(skip).Take(elementos).ToList())
            {
                TecnicoWrapper w = TecnicoToWrapper(u);
                rw.Add(w);
            }

            return Json(rw, JsonRequestBehavior.AllowGet);
        }


        private TecnicoWrapper TecnicoToWrapper(Entidad e)
        {
            TecnicoWrapper aw = new TecnicoWrapper();
            aw.Clave = e.EntidadClave.ToString();
            aw.Nombre = e.Nombre;
            aw.catEntidadTipoClave = e.catEntidadTipoClave.ToString();
            aw.EntidadPadreClave = e.EntidadPadreClave.ToString();

            try
            {
                PuestoTecnico pt = e.PuestoTecnico;
                aw.PuestoTecnicos = pt.catPuestoTecnico.Descripcion;
                aw.catPuestosTecnicosClave = pt.catPuestosTecnicosClave.ToString();
            }
            catch
            {
                aw.PuestoTecnicos = String.Empty;
                aw.catPuestosTecnicosClave = String.Empty;
            }

            aw.catDistribuidorClave = e.catDistribuidorClave.ToString();

            aw.Activo = Convert.ToInt32(e.Activo).ToString();

            return aw;
        }



        public ActionResult prueba()
        {


            if (Request["tecnico"] == null)
            {
                return Content("");
            }


            string cuales = Request["tecnico"].ToString();

            


            List<MultiusosWrapper> lista = new List<MultiusosWrapper>();
            DataTable dt = new DataTable();
            lista = getexcel(cuales);
            foreach (var l in lista)
            {
                DumpExcel(l.listadetablas, l.variable1, l.variable2);
            }

            return Content(null);
        }



        private void DumpExcel(List<DataTablesInventarioWrapper> lista, string almacen, string distribuidor)
        {
            using (ExcelPackage pck = new ExcelPackage())
            {



                foreach (var tbl in lista)
                {
                //Create the worksheet
                ExcelWorksheet ws = pck.Workbook.Worksheets.Add(tbl.Tecnico.ToString());
               
                //Load the datatable into the sheet, starting from cell A1. Print the column names on row 1
                ws.Cells["A4"].LoadFromDataTable(tbl.TablaInventario, true);

                //Format the header for column 1-3



                using (ExcelRange rng = ws.Cells["A4:G4"])
                {
                    rng.Style.Font.Bold = true;
                    rng.Style.Fill.PatternType = ExcelFillStyle.Solid;                      //Set Pattern for the background to Solid
                    rng.Style.Fill.BackgroundColor.SetColor(Color.FromArgb(79, 129, 189));  //Set color to dark blue
                    rng.Style.Font.Color.SetColor(Color.White);


                }
                //estilo a datos de plantilla
                using (ExcelRange rng = ws.Cells["A1:G3"])
                {
                    rng.Style.Font.Bold = true;
                    rng.Style.Fill.PatternType = ExcelFillStyle.Solid;                      //Set Pattern for the background to Solid
                    rng.Style.Fill.BackgroundColor.SetColor(Color.FromArgb(79, 129, 189));  //Set color to dark blue
                    rng.Style.Font.Color.SetColor(Color.White);


                }
                using (ExcelRange rng = ws.Cells["A1:G1"])
                {
                    rng.Style.Font.Bold = true;
                    rng.Style.Fill.PatternType = ExcelFillStyle.Solid;                      //Set Pattern for the background to Solid
                    rng.Style.Fill.BackgroundColor.SetColor(Color.Red);  //Set color to dark blue
                    rng.Style.Font.Color.SetColor(Color.White);


                }



                ws.Column(1).Width = 30;
                ws.Column(2).Width = 30;
                ws.Column(3).Width = 25;
                ws.Column(4).Width = 25;
                ws.Column(5).Width = 25;
                ws.Column(6).Width = 25;
                ws.Column(6).Width = 35;
                ws.Column(7).Width = 25;


                //datos de plantilla
                ws.Cells["A1"].Value = "";
                ws.Cells["B1"].Value = " REPORTE SALDO DE TECNICOS ";
              
                ws.Cells["A2"].Value = "DISTRIBUIDOR :";
                ws.Cells["B2"].Value = distribuidor;
                ws.Cells["C2"].Value = "ALMACEN :";
               // ws.Cells["D2"].Value = almacen;

                ws.Cells["A3"].Value = "NOMBRE DE TECNICO:";
                ws.Cells["B3"].Value = tbl.Tecnico.ToString();
               





                //Example how to Format Column 1 as numeric 
                using (ExcelRange col = ws.Cells[5, 1, 5 + tbl.TablaInventario.Rows.Count, 1])
                {
                    //col.Style.Numberformat.Format = "#,##0.00";
                    col.Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;

                }


                }

                //Write it back to the client
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;  filename=ExcelDemo.xlsx");
                Response.BinaryWrite(pck.GetAsByteArray());
            }
        }





        private List<MultiusosWrapper> getexcel(string cuales)
        {

            MultiusosWrapper mu = new MultiusosWrapper();
            ModeloAlmacen dc = new ModeloAlmacen();
            string[] t = cuales.ToString().Split(',');

web/Views/SaldoTecnico/Detalle.cshtml
<link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css' />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/bootstrap.css?1422792965" />
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/materialadmin.css?1425466319" />
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/font-awesome.min.css?1422529194" />
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/theme-default/material-design-iconic-font.min.css?1421434286" />
<!-- END STYLESHEETS -->


@{
    ViewBag.Title = "Detalle";

}

<script>
    $(document).ready(function () {
        $("body").tooltip({ selector: '[data-toggle=tooltip]' });       

    });


</script>


<a href="@Url.Action("Lista", "SaldoTecnico")" class=" btn ink-reaction btn-floating-action btn-success" data-toggle='tooltip' data-placement='right' title='' data-original-title='Regresa al reporte' style="position:absolute; top:100px;left:100px; ">
    <i class="fa fa-hand-o-left"></i>
</a>

@Html.Raw(ViewData["html"])

<script src="~/Content/assets/js/libs/jquery/jquery-migrate-1.2.1.min.js"></script>
<script src="~/Content/assets/js/libs/bootstrap/bootstrap.min.js"></script>
<script src="~/Content/assets/js/libs/toastr/toastr.js"></script>

web/Views/SaldoTecnico/Lista.cshtml
@{
    ViewBag.Title = "Lista";
    Layout = "~/Views/Shared/_Plantilla.cshtml";

    List<web.Models.catDistribuidor> distribuidor = (List<web.Models.catDistribuidor>)ViewData["distribuidor"];

    List<web.Models.catPuestoTecnico> puestostecnico = (List<web.Models.catPuestoTecnico>)ViewData["puestostecnico"];
}

<div class="card">

    <div class="card-head style-default-light" style="padding-top:10px; padding-left:10px;">
        <header>
            <strong style="font-weight:bold; border:none;">Saldo de técnicos</strong>
            <br /><small class="text-muted" style="font-size:14px;"> <a href="#"><i class="fa fa-home" aria-hidden="true"></i> Inicio</a>><a href="#" class="paginaActiva">Inventario</a></small>

        </header>
        <div class="tools">
            <div class="btn-group">
                <div class="btn-group open">
                    <a href="#" class="btn btn-icon-toggle dropdown-toggle" data-toggle="dropdown" aria-expanded="true"><i class="md md-content-paste"></i></a>
                    <ul class="dropdown-menu animation-dock pull-right" role="menu" style="text-align: left;">

                       
                        <li><a href="javascript:void(0); " id="pdf"><i class="fa fa-circle fa-fw text-default-dark"></i>Formato PDF</a></li>
                        <li><a href="javascript:void(0); " id="excel"><i class="fa fa-circle fa-fw text-default-dark"></i>Excel</a></li>
                        @*<li><a href="javascript:void(0);" id="obtenexcel"><i class="fa fa-circle fa-fw text-muted"></i> Formato Excel</a></li>*@

                    </ul>
                </div>
                <a class="btn btn-icon-toggle btn-refresh"><i class="md md-refresh"></i></a>
                <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>

            </div>

            @*<button class="btn btn-info btn-sm" id="pdfrecepcion">Descargar reporte</button>*@
        </div>
    </div>

    <div class="card-body">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="form-group">
                <div class="col-md-8">
                    Selecciona distribuidor:
                    <select id="distribuidor" class="form-control" style="">
                        @foreach (var a in distribuidor)
                        {
                            <option value="@a.catDistribuidorClave">@a.Nombre</option>
                        }

                    </select>
                </div>
                

            </div>
            
            
            <a class="btn btn-icon-toggle btn-default" style="display:none" id="repo" href="#offcanvas-search" data-toggle="offcanvas" data-backdrop="false"> <i class="fa fa-ellipsis-v"></i></a>
            <table class="table" id="indice">
                <thead>
                    <tr>
                        <td>Selecciona</td>
                        <td>Técnico</td>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
           



        </div>
        <div class="col-md-2"></div>
        

    </div> 
   
    
</div>

<script src="~/Content/pags/ReporteSaldoTécnicos/listaTecnicos.js"></script>